era5_config:
  era5_uri: "arraylake://earthmover-public/era5"
  variables: [
    "geopotential",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "specific_humidity",
    "vertical_velocity",
    "potential_vorticity",
    "equivalent_potential_temperature",
    "virtual_temperature",
    "dewpoint_temperature",
    "relative_humidity",
    "potential_temperature",
    "mean_sea_level_pressure",
    "2m_temperature",
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "2m_dewpoint_temperature",
    "land_sea_mask",
    "geopotential_at_surface"
    ]
  pressure_levels: [1000, 925, 850, 700, 500, 300]
  time_start: "2007-01-01T00:00:00"
  time_end: "2025-12-31T23:59:00"
  time_resolution: "6h"
  coordinates: [0.25, 80, 130, 369.75]
  storage_options: null
  chunks: null
  zarr_async_concurrency: 128

icechunk_storage_config:
  store_path: "/ourdisk/hpc/ai2es/tman/data/fronts/train"
  branch_name: "main"
  commit_message: "Add ERA5 data from Arraylake 2007-2025"
  group_name: "era5"
  write_batch_size: 1000

slurm_config:
  queue: "ai2es"
  cores: 128
  processes: 32
  memory: "288GB"
  walltime: "72:00:00"
  stdout: "/ourdisk/hpc/ai2es/tman/logs/generate_%j_out.txt"
  stderr: "/ourdisk/hpc/ai2es/tman/logs/generate_%j_err.txt"
  n_jobs: 1
