run_name: ablation_pv_and_theta_e

data_config:
  inputs_icechunk_config:
    store_path: "/ourdisk/hpc/ai2es/tman/data/fronts/train/"
    branch_name: "main"
    group_name: "era5"
  targets_icechunk_config:
    store_path: "/ourdisk/hpc/ai2es/tman/restructured_front_data/icechunk"
    branch_name: "main"
    virtual_chunk_local_path: "/ourdisk/hpc/ai2es/tman/restructured_front_data/netcdf/"
  batch_size: 32
  test_years: [2019]
  val_years: [2018]
  max_queue_size: 16
  class_weights: [0.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  front_dilation: 1
  time_resolution: "6h" # USAD fronts are only 6-hourly; CONUS is 3-hourly
  volume_inputs: true  # batches shaped (batch, lat, lon, level, variable) for Conv3D
  variables:
    [
      "equivalent_potential_temperature",
      "u_component_of_wind",
      "v_component_of_wind",
      "specific_humidity",
      "potential_vorticity",
    ]
  norm_stats_cache_dir: "/ourdisk/hpc/ai2es/tman/data/fronts/norm_stats_cache"
  normalization_method: minmax
  max_pydataset_workers: 16  # Number of threads used by tf.keras.utils.PyDataset to load batches in parallel

eval_config:
  model_path: "/ourdisk/hpc/ai2es/tman/models/${run_name}/_best_loss.keras"
  outdir: "/ourdisk/hpc/ai2es/tman/models/stats/${run_name}/"
  front_types: [CF, WF, SF, OF, DL]
  front_dilation: 1  # match training dilation
  time_start: "2024-01-01T00:00:00"
  time_end: "2024-12-31T18:00:00"

predict_config:
  model_path: "/ourdisk/hpc/ai2es/tman/models/${run_name}/_best_loss.keras"
  outdir: "/ourdisk/hpc/ai2es/tman/models/case_studies/${run_name}/"
  init_time: "2024-03-15T06:00:00"
  front_types: [CF, WF, SF, OF, DL]
  filled_contours: true
  targets: true
